/*
 * This file is generated by jOOQ.
 */
package com.example.demo.orders.domain.model.entites;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 商品資料
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "orders_detail",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_orders_detail_PRIMARY", columnNames = { "ser_id" })
    },
    indexes = {
        @Index(name = "order_id", columnList = "order_id ASC")
    }
)
public class OrdersDetail implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        serId;
    private String        orderId;
    private String        goodsId;
    private String        goodsName;
    private Integer       count;
    private Integer       version;
    private String        createdBy;
    private LocalDateTime createdDate;
    private String        lastModifiedBy;
    private LocalDateTime lastModifiedDate;

    public OrdersDetail() {}

    public OrdersDetail(OrdersDetail value) {
        this.serId = value.serId;
        this.orderId = value.orderId;
        this.goodsId = value.goodsId;
        this.goodsName = value.goodsName;
        this.count = value.count;
        this.version = value.version;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public OrdersDetail(
        String        serId,
        String        orderId,
        String        goodsId,
        String        goodsName,
        Integer       count,
        Integer       version,
        String        createdBy,
        LocalDateTime createdDate,
        String        lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        this.serId = serId;
        this.orderId = orderId;
        this.goodsId = goodsId;
        this.goodsName = goodsName;
        this.count = count;
        this.version = version;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * Getter for <code>testdb.orders_detail.ser_id</code>. 流水號
     */
    @Id
    @Column(name = "ser_id", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getSerId() {
        return this.serId;
    }

    /**
     * Setter for <code>testdb.orders_detail.ser_id</code>. 流水號
     */
    public void setSerId(String serId) {
        this.serId = serId;
    }

    /**
     * Getter for <code>testdb.orders_detail.order_id</code>. 訂單編號
     */
    @Column(name = "order_id", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>testdb.orders_detail.order_id</code>. 訂單編號
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * Getter for <code>testdb.orders_detail.goods_id</code>. 商品編號
     */
    @Column(name = "goods_id", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getGoodsId() {
        return this.goodsId;
    }

    /**
     * Setter for <code>testdb.orders_detail.goods_id</code>. 商品編號
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * Getter for <code>testdb.orders_detail.goods_name</code>. 商品名稱
     */
    @Column(name = "goods_name", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getGoodsName() {
        return this.goodsName;
    }

    /**
     * Setter for <code>testdb.orders_detail.goods_name</code>. 商品名稱
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * Getter for <code>testdb.orders_detail.count</code>. 數量
     */
    @Column(name = "count", nullable = false, precision = 10)
    @NotNull
    public Integer getCount() {
        return this.count;
    }

    /**
     * Setter for <code>testdb.orders_detail.count</code>. 數量
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * Getter for <code>testdb.orders_detail.version</code>. 版本鎖
     */
    @Version
    @Column(name = "version", nullable = false, precision = 10)
    @NotNull
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>testdb.orders_detail.version</code>. 版本鎖
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * Getter for <code>testdb.orders_detail.created_by</code>.
     */
    @Column(name = "created_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>testdb.orders_detail.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>testdb.orders_detail.created_date</code>.
     */
    @Column(name = "created_date", nullable = false)
    @NotNull
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>testdb.orders_detail.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>testdb.orders_detail.last_modified_by</code>.
     */
    @Column(name = "last_modified_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>testdb.orders_detail.last_modified_by</code>.
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * Getter for <code>testdb.orders_detail.last_modified_date</code>.
     */
    @Column(name = "last_modified_date", nullable = false)
    @NotNull
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>testdb.orders_detail.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}
