/*
 * This file is generated by jOOQ.
 */
package com.example.demo.orders.domain.model.entites;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 訂單資料
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "orders",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_orders_PRIMARY", columnNames = { "order_id" })
    }
)
public class Orders implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        orderId;
    private String        customerName;
    private Integer       totalAmount;
    private Integer       version;
    private String        createdBy;
    private LocalDateTime createdDate;
    private String        lastModifiedBy;
    private LocalDateTime lastModifiedDate;

    public Orders() {}

    public Orders(Orders value) {
        this.orderId = value.orderId;
        this.customerName = value.customerName;
        this.totalAmount = value.totalAmount;
        this.version = value.version;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public Orders(
        String        orderId,
        String        customerName,
        Integer       totalAmount,
        Integer       version,
        String        createdBy,
        LocalDateTime createdDate,
        String        lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        this.orderId = orderId;
        this.customerName = customerName;
        this.totalAmount = totalAmount;
        this.version = version;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * Getter for <code>testdb.orders.order_id</code>. 訂單編號
     */
    @Id
    @Column(name = "order_id", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>testdb.orders.order_id</code>. 訂單編號
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * Getter for <code>testdb.orders.customer_name</code>. 客戶姓名
     */
    @Column(name = "customer_name", nullable = false, length = 20)
    @NotNull
    @Size(max = 20)
    public String getCustomerName() {
        return this.customerName;
    }

    /**
     * Setter for <code>testdb.orders.customer_name</code>. 客戶姓名
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * Getter for <code>testdb.orders.total_amount</code>. 訂單金額
     */
    @Column(name = "total_amount", nullable = false, precision = 10)
    @NotNull
    public Integer getTotalAmount() {
        return this.totalAmount;
    }

    /**
     * Setter for <code>testdb.orders.total_amount</code>. 訂單金額
     */
    public void setTotalAmount(Integer totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * Getter for <code>testdb.orders.version</code>. 版本鎖
     */
    @Version
    @Column(name = "version", nullable = false, precision = 10)
    @NotNull
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>testdb.orders.version</code>. 版本鎖
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * Getter for <code>testdb.orders.created_by</code>.
     */
    @Column(name = "created_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>testdb.orders.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>testdb.orders.created_date</code>.
     */
    @Column(name = "created_date", nullable = false)
    @NotNull
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>testdb.orders.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>testdb.orders.last_modified_by</code>.
     */
    @Column(name = "last_modified_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>testdb.orders.last_modified_by</code>.
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * Getter for <code>testdb.orders.last_modified_date</code>.
     */
    @Column(name = "last_modified_date", nullable = false)
    @NotNull
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>testdb.orders.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}
