/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.demo.orders.interfaces.rest;

import com.example.demo.orders.interfaces.rest.dto.OrderCreateDto;
import com.example.demo.orders.interfaces.rest.dto.OrderViewDto;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-06-03T23:37:39.299902+08:00[Asia/Taipei]")
@Validated
@Api(value = "Order", description = "the Order API")
public interface OrderApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /orders : 建立訂單
     * 建立訂單
     *
     * @param orderCreateDto  (optional)
     * @return Created (status code 201)
     */
    @ApiOperation(value = "建立訂單", nickname = "postOrders", notes = "建立訂單", response = OrderViewDto.class, authorizations = {
        
        @Authorization(value = "JWT")
         }, tags={ "Order", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = OrderViewDto.class) })
    @PostMapping(
        value = "/orders",
        produces = "application/json",
        consumes = "application/json"
    )
    default ResponseEntity<OrderViewDto> postOrders(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) OrderCreateDto orderCreateDto) throws Exception {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"totalAmount\" : 0, \"orderId\" : \"orderId\", \"goods\" : [ { \"unitPrice\" : 6, \"goodsId\" : \"goodsId\", \"count\" : 1, \"goodsName\" : \"goodsName\" }, { \"unitPrice\" : 6, \"goodsId\" : \"goodsId\", \"count\" : 1, \"goodsName\" : \"goodsName\" } ], \"customerName\" : \"customerName\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
